### PR TITLE
Ts node support

### PR DESCRIPTION
**Pull request by chgeo**

### CODE REVIEW

**Comment by Kkoile** [comment]
Unfortunately I was still not able to get the existing tests running with the current master version of cds. Neither with jest 26 or 27.

**Comment by chgeo** [comment]
> Unfortunately I was still not able to get the existing tests running with the current master version of cds. Neither with jest 26 or 27.

Yes, that's what I observe as well.  Needs more investigation...

**Comment by chgeo** [comment]
@Kkoile can you allow [edits from maintainers](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for this PR?

**Comment by tsteckenborn** [comment]
> > Unfortunately I was still not able to get the existing tests running with the current master version of cds. Neither with jest 26 or 27.
> 
> Yes, that's what I observe as well. Needs more investigation...

I have not tested it in this repository, but in general, it seems to work with Jest using jasmine2 as test runner. With Jest 27, the default test runner was changed to jest-circus (see [here](https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults)). The problem is probably related to this. There were some changes that can lead to errors, see for example [here](https://github.com/facebook/jest/issues/10529).

**Comment by chgeo** [comment]
Had a closer look and some findings.

Turns out there is an error on server startup that sap/cds swallows:
```
$  TYPESCRIPT_SUPPORT=true npx jest@^26 -- --preset ts-jest --testMatch test/*.test.ts
 FAIL  test/hello-world-ts.test.ts
  Hello world!
    ✕ should say hello with class impl from a typescript file (147 ms)

  ● Hello world! › should say hello with class impl from a typescript file

    SyntaxError: /Users/.../cap/samples/hello/world.ts: Unexpected token, expected "," (2:13)

      1 | module.exports = class say {
    > 2 |     hello(req: any) {
        |              ^
      3 |         return `Hello ${req.data.to} from a typescript file!`
      4 |     }
      5 | }

      at Parser._raise (../../node_modules/@babel/parser/src/parser/error.js:134:45)
      at Parser.raiseWithData (../../node_modules/@babel/parser/src/parser/error.js:129:17)
      at Parser.raise (../../node_modules/@babel/parser/src/parser/error.js:78:17)
      at Parser.unexpected (../../node_modules/@babel/parser/src/parser/util.js:179:16)
      at Parser.expect (../../node_modules/@babel/parser/src/parser/util.js:144:28)
      at Parser.parseBindingList (../../node_modules/@babel/parser/src/parser/lval.js:315:14)
      at Parser.parseFunctionParams (../../node_modules/@babel/parser/src/parser/statement.js:1207:24)
      at Parser.parseMethod (../../node_modules/@babel/parser/src/parser/expression.js:2063:10)
      at Parser.pushClassMethod (../../node_modules/@babel/parser/src/parser/statement.js:1655:12)
      at Parser.parseClassMemberWithIsStatic (../../node_modules/@babel/parser/src/parser/statement.js:1479:12)
```
→ This actually looks like `ts-jest` is not active
→ Will fix the error reporting separately

This changes if one configures the preset in package.json:
```json
  "jest": {
    "testEnvironment": "node",
    "preset": "ts-jest"
  }
```
results in 
```
 FAIL  test/hello-world-ts.test.ts
  ● Test suite failed to run

    TypeError: Jest: a transform must export a `process` function.

      at ScriptTransformer._getTransformer (../../node_modules/@jest/transform/build/ScriptTransformer.js:360:13)
      at ScriptTransformer.transformSource (../../node_modules/@jest/transform/build/ScriptTransformer.js:427:28)
      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:569:40)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:607:25)
```

Now something is wrong w/ the `ts-jest` or its config.
→ @Kkoile maybe you can take it from here

**Comment by chgeo** [comment]
I have pulled this over to PR https://github.com/SAP-samples/cloud-cap-samples/pull/248 in the original repo.
See there for more.

**Pull request closed without merging**
