### PR TITLE
Important Cleanup

### PR DESCRIPTION
**Pull request by danjoa**
This is ... 

1. restoring the former conciseness and simplicity of `./bookshop` → as also documented: 
    - it is meant to demonstrate the best practice of services serving denormalised views
    - and should intentionally not browse to and serve Authors  
2. moving db-specific calculated fields to `./fiori` as they are used there
    - also moved the workaround with the virtual fields to `fiori.cds` to address that locally 
    - (just took us hours to find out why we did that workaround in the other place)
4. have an admin app for Authors instead of a browse only one

@gregorwolf

### CODE REVIEW

**Review by stewsk — COMMENTED** [review]
There is a code tour explaining the handling of db-specific extensions:
https://github.com/SAP-samples/cloud-cap-samples/blob/main/.tours/db-native.tour
-> needs to be adapted when moving the respective code to fiori

**Comment by chgeo** [comment]
> There is a code tour explaining the handling of db-specific extensions:

Yes, I am aware, but can also do this in a second PR in case you don't want to wait for it.

**Review by chgeo — APPROVED** [review]

**Review by stewsk — APPROVED** [review]

**Comment by danjoa** [comment]
What is this f*****g DCO task failure? → do I have to repeat that exercise again and again? If yes, this is likely the best possible way to avoid contributions. 😠

**Comment by danjoa** [comment]
Thanks for detecting and fixing the broken code tour ... → yet we need to adjust more of those links, and much **more important**:  it was wrong (my mistake)

**Don't** extend `requires.db` like that: 
```json
      "db": {
        "kind": "sql",
        "[development]": { "model": "db/sqlite" },
        "[production]": { "model": "db/hana" }
      },
```

But add a separate `requires.<whatever>` entry like that: 

```json
      "db-ext": {
        "[development]": { "model": "db/sqlite" },
        "[production]": { "model": "db/hana" }
      },
```

Reason: The former has the effect that a subsequent `cds deploy -2 sqlite` would only `cds.load` the model from `db/sqlite` instead of doing a `cds.load('*')` which would include all, including `db/sqlite`.

**Comment by chgeo** [comment]
> That entry is a pseudo datasource, its name doesn't matter → using something like db-ext seems adequate

I see.  I will added that hint + a link to `cds.resolve` to the code tour explanation, otherwise it might hard to understand what it does and why it's picked up.

**Comment by chgeo** [comment]
> What is this DCO task failure? → do I have to repeat that exercise again and again? If yes, this is likely the best possible way to avoid contributions. 

We haven't configured it; it happened to appear automatically.  Guess it was configured by SAP-samples admins.

@btbernard is the DCO check now a standard?  Haven't seen it in other (non-SAP) projects, so I wonder why we need it.  Looks like another maintenance overhead generator for us committers, as we don't expect our contributors to always add a sign-off line.

**Pull request merged**
