### PR TITLE
[graphql] rm server.js with cds^5.8.3

### PR DESCRIPTION
**Pull request by sjvans**

### CODE REVIEW

**Review by chgeo — CHANGES_REQUESTED** [review]
5.8.3 is not yet available.  
If so, please also update package-lock.json with `npm update`

**Comment by chgeo** [comment]
5.8.3 is now in (#329)

**Review by chgeo — APPROVED** [review]
@sjvans fine with me

**Comment by johannes-vogel** [comment]
There's no package.json in graphql branch. Should we create it?

**Comment by chgeo** [comment]
There is one: https://github.com/SAP-samples/cloud-cap-samples/blob/graphql/graphql/package.json ?

**Comment by johannes-vogel** [comment]
Sorry, I meant package-lock :)

**Comment by chgeo** [comment]
Yes.. might be that `graphql` is so much behind `main` that it does not have a package-lock yet.  Can be solved by merging main to `graphql` (tbd in separate PR).

**Pull request merged**
