### PR TITLE
Patch of _reduceStock() under @sap/cds 4

### PR DESCRIPTION
**Pull request by laszloKajan**
With the new versions of @sap/cds, the previous implementation of "async function _reduceStock (req)" is no longer valid: it results in an internal server error 500. This patch fixes that.

### CODE REVIEW

**Comment by chgeo** [comment]
Thanks for catching this.  I have done some further cosmetics to the code.
Also removed the additional dependencies introduced in your commit, as they are off-topic.

We will anyways update the openSAP code to cds 4 soon.

**Comment by laszloKajan** [comment]
@chgeo The OpenSAP course was fantastic, we use these samples very often.
But I can't find the documentation for 'cds.transaction(req).run(<array>)' that you use in your code. The CAPM docs [1] don't seem to offer this option for srv.run(...). That's why I used map( run(<one UPDATE>) for each item ) instead.
[1] https://cap.cloud.sap/docs/node.js/api

**Comment by chgeo** [comment]
@johannes-vogel can you or someone from your team check on the docs and add the `cds.run([...])` variant?

**Comment by johannes-vogel** [comment]
@chgeo Yes, we'll take care of it.

**Comment by laszloKajan** [comment]
@chgeo @johannes-vogel Thank you very much in advance!

**Pull request merged**
